import './globals.css'
import { Open_Sans } from 'next/font/google';

const openSans = Open_Sans({
  subsets: ["latin"]
})

export const metadata = {
  title: 'Chat GPT Blog',
  description: 'Generated by Next Js and AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={openSans.className} lang="en">
      <body>{children}</body>
    </html>
  )
}
